[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200